apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-app deployment
  labels:
    app: front-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
        - name: info910-front-web
          image: ghcr.io/chatelant/info910-front:main
          ports:
            - containerPort: 8080